# Generated by Django 5.1.3 on 2024-11-28 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_remove_resource_file_alter_resource_resource_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='description',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='title',
        ),
    ]
