# Generated by Django 5.1.3 on 2024-11-30 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_rename_description_assignment_question_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourcefile',
            name='title',
            field=models.CharField(default='Grep', max_length=50),
            preserve_default=False,
        ),
    ]
