# Generated by Django 5.1.3 on 2024-11-30 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_resourcefile_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resourcefile',
            name='title',
        ),
    ]
